run-dist:
	@./build/install/app/bin app

run-dist-h:
	@./build/install/app/bin app -h

run:
	@./gradlew run

report:
	@./gradlew jacocoTestReport

build:
	@./gradlew clean build

install:
	@./gradlew clean installDist

.PHONY: build
